version: '3'
services:
  some-rabbit:
    image: rabbitmq:3-management
    container_name: some-rabbit
    hostname: some-rabbit
    network_mode: "bridge"
    restart: always
    environment:
      - RABBITMQ_DEFAULT_USER=user
      - RABBITMQ_DEFAULT_PASS=password
    ports:
      - "15672:15672"
      - "5672:5672"


  producer-payment:
    image: producer-payment:0.0.1
    container_name: producer-payment
    hostname: producer-payment
    network_mode: "bridge"
    restart: always
    environment:
      - RABBITMQ_PORT=5672
      - RABBITMQ_HOST=some-rabbit
    ports:
      - "8001:8080"
    depends_on:
      - some-rabbit
    links:
      - some-rabbit:some-rabbit


  consumer-payment:
    image: consumer-payment:0.0.1
    container_name: consumer-payment
    hostname: consumer-payment
    network_mode: "bridge"
    restart: always
    environment:
      - RABBITMQ_PORT=5672
      - RABBITMQ_HOST=some-rabbit
    ports:
      - "8002:8080"
    depends_on:
      - some-rabbit
    links:
      - some-rabbit:some-rabbit



